# Generated by Django 4.1 on 2023-09-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('AccountID', models.AutoField(db_column='AccountID', primary_key=True, serialize=False)),
                ('PassWord', models.CharField(db_column='PassWord', max_length=20)),
                ('UserName', models.CharField(db_column='UserName', max_length=20)),
                ('Authority', models.IntegerField(db_column='Authority')),
                ('ProfileID', models.IntegerField(db_column='ProfileID')),
            ],
            options={
                'db_table': 'Account',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('ProfileID', models.AutoField(db_column='ProfileID', primary_key=True, serialize=False)),
                ('Email', models.CharField(db_column='Email', max_length=20)),
                ('Phone', models.CharField(db_column='Phone', max_length=20)),
                ('SecureLevel', models.IntegerField(db_column='SecureLevel')),
                ('BrithDate', models.DateTimeField(db_column='BrithDate')),
            ],
            options={
                'db_table': 'Profile',
            },
        ),
    ]
